// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/ProtocolBuffer.proto

public final class ProtocolBuffer {
  private ProtocolBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class InstantMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use InstantMessage.newBuilder() to construct.
    private InstantMessage() {
      initFields();
    }
    private InstantMessage(boolean noInit) {}
    
    private static final InstantMessage defaultInstance;
    public static InstantMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public InstantMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolBuffer.internal_static_InstantMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolBuffer.internal_static_InstantMessage_fieldAccessorTable;
    }
    
    // required string contents = 1;
    public static final int CONTENTS_FIELD_NUMBER = 1;
    private boolean hasContents;
    private java.lang.String contents_ = "";
    public boolean hasContents() { return hasContents; }
    public java.lang.String getContents() { return contents_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasContents) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasContents()) {
        output.writeString(1, getContents());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasContents()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getContents());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ProtocolBuffer.InstantMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.InstantMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.InstantMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.InstantMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.InstantMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.InstantMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.InstantMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.InstantMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.InstantMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.InstantMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtocolBuffer.InstantMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ProtocolBuffer.InstantMessage result;
      
      // Construct using ProtocolBuffer.InstantMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ProtocolBuffer.InstantMessage();
        return builder;
      }
      
      protected ProtocolBuffer.InstantMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ProtocolBuffer.InstantMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocolBuffer.InstantMessage.getDescriptor();
      }
      
      public ProtocolBuffer.InstantMessage getDefaultInstanceForType() {
        return ProtocolBuffer.InstantMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ProtocolBuffer.InstantMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ProtocolBuffer.InstantMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ProtocolBuffer.InstantMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ProtocolBuffer.InstantMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocolBuffer.InstantMessage) {
          return mergeFrom((ProtocolBuffer.InstantMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtocolBuffer.InstantMessage other) {
        if (other == ProtocolBuffer.InstantMessage.getDefaultInstance()) return this;
        if (other.hasContents()) {
          setContents(other.getContents());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setContents(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string contents = 1;
      public boolean hasContents() {
        return result.hasContents();
      }
      public java.lang.String getContents() {
        return result.getContents();
      }
      public Builder setContents(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasContents = true;
        result.contents_ = value;
        return this;
      }
      public Builder clearContents() {
        result.hasContents = false;
        result.contents_ = getDefaultInstance().getContents();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:InstantMessage)
    }
    
    static {
      defaultInstance = new InstantMessage(true);
      ProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:InstantMessage)
  }
  
  public static final class PublicKey extends
      com.google.protobuf.GeneratedMessage {
    // Use PublicKey.newBuilder() to construct.
    private PublicKey() {
      initFields();
    }
    private PublicKey(boolean noInit) {}
    
    private static final PublicKey defaultInstance;
    public static PublicKey getDefaultInstance() {
      return defaultInstance;
    }
    
    public PublicKey getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolBuffer.internal_static_PublicKey_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolBuffer.internal_static_PublicKey_fieldAccessorTable;
    }
    
    // required string encoding = 1;
    public static final int ENCODING_FIELD_NUMBER = 1;
    private boolean hasEncoding;
    private java.lang.String encoding_ = "";
    public boolean hasEncoding() { return hasEncoding; }
    public java.lang.String getEncoding() { return encoding_; }
    
    // required bytes public_key = 2;
    public static final int PUBLIC_KEY_FIELD_NUMBER = 2;
    private boolean hasPublicKey;
    private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPublicKey() { return hasPublicKey; }
    public com.google.protobuf.ByteString getPublicKey() { return publicKey_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasEncoding) return false;
      if (!hasPublicKey) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasEncoding()) {
        output.writeString(1, getEncoding());
      }
      if (hasPublicKey()) {
        output.writeBytes(2, getPublicKey());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasEncoding()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getEncoding());
      }
      if (hasPublicKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPublicKey());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ProtocolBuffer.PublicKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.PublicKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.PublicKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.PublicKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.PublicKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.PublicKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.PublicKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.PublicKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.PublicKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.PublicKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtocolBuffer.PublicKey prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ProtocolBuffer.PublicKey result;
      
      // Construct using ProtocolBuffer.PublicKey.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ProtocolBuffer.PublicKey();
        return builder;
      }
      
      protected ProtocolBuffer.PublicKey internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ProtocolBuffer.PublicKey();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocolBuffer.PublicKey.getDescriptor();
      }
      
      public ProtocolBuffer.PublicKey getDefaultInstanceForType() {
        return ProtocolBuffer.PublicKey.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ProtocolBuffer.PublicKey build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ProtocolBuffer.PublicKey buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ProtocolBuffer.PublicKey buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ProtocolBuffer.PublicKey returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocolBuffer.PublicKey) {
          return mergeFrom((ProtocolBuffer.PublicKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtocolBuffer.PublicKey other) {
        if (other == ProtocolBuffer.PublicKey.getDefaultInstance()) return this;
        if (other.hasEncoding()) {
          setEncoding(other.getEncoding());
        }
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setEncoding(input.readString());
              break;
            }
            case 18: {
              setPublicKey(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required string encoding = 1;
      public boolean hasEncoding() {
        return result.hasEncoding();
      }
      public java.lang.String getEncoding() {
        return result.getEncoding();
      }
      public Builder setEncoding(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEncoding = true;
        result.encoding_ = value;
        return this;
      }
      public Builder clearEncoding() {
        result.hasEncoding = false;
        result.encoding_ = getDefaultInstance().getEncoding();
        return this;
      }
      
      // required bytes public_key = 2;
      public boolean hasPublicKey() {
        return result.hasPublicKey();
      }
      public com.google.protobuf.ByteString getPublicKey() {
        return result.getPublicKey();
      }
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPublicKey = true;
        result.publicKey_ = value;
        return this;
      }
      public Builder clearPublicKey() {
        result.hasPublicKey = false;
        result.publicKey_ = getDefaultInstance().getPublicKey();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PublicKey)
    }
    
    static {
      defaultInstance = new PublicKey(true);
      ProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PublicKey)
  }
  
  public static final class ClientInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use ClientInfo.newBuilder() to construct.
    private ClientInfo() {
      initFields();
    }
    private ClientInfo(boolean noInit) {}
    
    private static final ClientInfo defaultInstance;
    public static ClientInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolBuffer.internal_static_ClientInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolBuffer.internal_static_ClientInfo_fieldAccessorTable;
    }
    
    // optional string version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private boolean hasVersion;
    private java.lang.String version_ = "";
    public boolean hasVersion() { return hasVersion; }
    public java.lang.String getVersion() { return version_; }
    
    // optional string location = 2;
    public static final int LOCATION_FIELD_NUMBER = 2;
    private boolean hasLocation;
    private java.lang.String location_ = "";
    public boolean hasLocation() { return hasLocation; }
    public java.lang.String getLocation() { return location_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasVersion()) {
        output.writeString(1, getVersion());
      }
      if (hasLocation()) {
        output.writeString(2, getLocation());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getVersion());
      }
      if (hasLocation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getLocation());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ProtocolBuffer.ClientInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.ClientInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.ClientInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.ClientInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.ClientInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.ClientInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.ClientInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.ClientInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtocolBuffer.ClientInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ProtocolBuffer.ClientInfo result;
      
      // Construct using ProtocolBuffer.ClientInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ProtocolBuffer.ClientInfo();
        return builder;
      }
      
      protected ProtocolBuffer.ClientInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ProtocolBuffer.ClientInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocolBuffer.ClientInfo.getDescriptor();
      }
      
      public ProtocolBuffer.ClientInfo getDefaultInstanceForType() {
        return ProtocolBuffer.ClientInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ProtocolBuffer.ClientInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ProtocolBuffer.ClientInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ProtocolBuffer.ClientInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ProtocolBuffer.ClientInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocolBuffer.ClientInfo) {
          return mergeFrom((ProtocolBuffer.ClientInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtocolBuffer.ClientInfo other) {
        if (other == ProtocolBuffer.ClientInfo.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasLocation()) {
          setLocation(other.getLocation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setVersion(input.readString());
              break;
            }
            case 18: {
              setLocation(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string version = 1;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public java.lang.String getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = getDefaultInstance().getVersion();
        return this;
      }
      
      // optional string location = 2;
      public boolean hasLocation() {
        return result.hasLocation();
      }
      public java.lang.String getLocation() {
        return result.getLocation();
      }
      public Builder setLocation(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLocation = true;
        result.location_ = value;
        return this;
      }
      public Builder clearLocation() {
        result.hasLocation = false;
        result.location_ = getDefaultInstance().getLocation();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ClientInfo)
    }
    
    static {
      defaultInstance = new ClientInfo(true);
      ProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ClientInfo)
  }
  
  public static final class RegisterKeyReq extends
      com.google.protobuf.GeneratedMessage {
    // Use RegisterKeyReq.newBuilder() to construct.
    private RegisterKeyReq() {
      initFields();
    }
    private RegisterKeyReq(boolean noInit) {}
    
    private static final RegisterKeyReq defaultInstance;
    public static RegisterKeyReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegisterKeyReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolBuffer.internal_static_RegisterKeyReq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolBuffer.internal_static_RegisterKeyReq_fieldAccessorTable;
    }
    
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private boolean hasUsername;
    private java.lang.String username_ = "";
    public boolean hasUsername() { return hasUsername; }
    public java.lang.String getUsername() { return username_; }
    
    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private boolean hasPassword;
    private java.lang.String password_ = "";
    public boolean hasPassword() { return hasPassword; }
    public java.lang.String getPassword() { return password_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasUsername) return false;
      if (!hasPassword) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasUsername()) {
        output.writeString(1, getUsername());
      }
      if (hasPassword()) {
        output.writeString(2, getPassword());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasUsername()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUsername());
      }
      if (hasPassword()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPassword());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ProtocolBuffer.RegisterKeyReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.RegisterKeyReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.RegisterKeyReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtocolBuffer.RegisterKeyReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ProtocolBuffer.RegisterKeyReq result;
      
      // Construct using ProtocolBuffer.RegisterKeyReq.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ProtocolBuffer.RegisterKeyReq();
        return builder;
      }
      
      protected ProtocolBuffer.RegisterKeyReq internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ProtocolBuffer.RegisterKeyReq();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocolBuffer.RegisterKeyReq.getDescriptor();
      }
      
      public ProtocolBuffer.RegisterKeyReq getDefaultInstanceForType() {
        return ProtocolBuffer.RegisterKeyReq.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ProtocolBuffer.RegisterKeyReq build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ProtocolBuffer.RegisterKeyReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ProtocolBuffer.RegisterKeyReq buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ProtocolBuffer.RegisterKeyReq returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocolBuffer.RegisterKeyReq) {
          return mergeFrom((ProtocolBuffer.RegisterKeyReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtocolBuffer.RegisterKeyReq other) {
        if (other == ProtocolBuffer.RegisterKeyReq.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setUsername(input.readString());
              break;
            }
            case 18: {
              setPassword(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string username = 1;
      public boolean hasUsername() {
        return result.hasUsername();
      }
      public java.lang.String getUsername() {
        return result.getUsername();
      }
      public Builder setUsername(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUsername = true;
        result.username_ = value;
        return this;
      }
      public Builder clearUsername() {
        result.hasUsername = false;
        result.username_ = getDefaultInstance().getUsername();
        return this;
      }
      
      // required string password = 2;
      public boolean hasPassword() {
        return result.hasPassword();
      }
      public java.lang.String getPassword() {
        return result.getPassword();
      }
      public Builder setPassword(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPassword = true;
        result.password_ = value;
        return this;
      }
      public Builder clearPassword() {
        result.hasPassword = false;
        result.password_ = getDefaultInstance().getPassword();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:RegisterKeyReq)
    }
    
    static {
      defaultInstance = new RegisterKeyReq(true);
      ProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RegisterKeyReq)
  }
  
  public static final class RegisterKeyRes extends
      com.google.protobuf.GeneratedMessage {
    // Use RegisterKeyRes.newBuilder() to construct.
    private RegisterKeyRes() {
      initFields();
    }
    private RegisterKeyRes(boolean noInit) {}
    
    private static final RegisterKeyRes defaultInstance;
    public static RegisterKeyRes getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegisterKeyRes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolBuffer.internal_static_RegisterKeyRes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolBuffer.internal_static_RegisterKeyRes_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ProtocolBuffer.RegisterKeyRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.RegisterKeyRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.RegisterKeyRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.RegisterKeyRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtocolBuffer.RegisterKeyRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ProtocolBuffer.RegisterKeyRes result;
      
      // Construct using ProtocolBuffer.RegisterKeyRes.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ProtocolBuffer.RegisterKeyRes();
        return builder;
      }
      
      protected ProtocolBuffer.RegisterKeyRes internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ProtocolBuffer.RegisterKeyRes();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocolBuffer.RegisterKeyRes.getDescriptor();
      }
      
      public ProtocolBuffer.RegisterKeyRes getDefaultInstanceForType() {
        return ProtocolBuffer.RegisterKeyRes.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ProtocolBuffer.RegisterKeyRes build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ProtocolBuffer.RegisterKeyRes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ProtocolBuffer.RegisterKeyRes buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ProtocolBuffer.RegisterKeyRes returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocolBuffer.RegisterKeyRes) {
          return mergeFrom((ProtocolBuffer.RegisterKeyRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtocolBuffer.RegisterKeyRes other) {
        if (other == ProtocolBuffer.RegisterKeyRes.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:RegisterKeyRes)
    }
    
    static {
      defaultInstance = new RegisterKeyRes(true);
      ProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RegisterKeyRes)
  }
  
  public static final class IdentifyKeyReq extends
      com.google.protobuf.GeneratedMessage {
    // Use IdentifyKeyReq.newBuilder() to construct.
    private IdentifyKeyReq() {
      initFields();
    }
    private IdentifyKeyReq(boolean noInit) {}
    
    private static final IdentifyKeyReq defaultInstance;
    public static IdentifyKeyReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public IdentifyKeyReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolBuffer.internal_static_IdentifyKeyReq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolBuffer.internal_static_IdentifyKeyReq_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ProtocolBuffer.IdentifyKeyReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.IdentifyKeyReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.IdentifyKeyReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.IdentifyKeyReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.IdentifyKeyReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.IdentifyKeyReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.IdentifyKeyReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.IdentifyKeyReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.IdentifyKeyReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.IdentifyKeyReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtocolBuffer.IdentifyKeyReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ProtocolBuffer.IdentifyKeyReq result;
      
      // Construct using ProtocolBuffer.IdentifyKeyReq.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ProtocolBuffer.IdentifyKeyReq();
        return builder;
      }
      
      protected ProtocolBuffer.IdentifyKeyReq internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ProtocolBuffer.IdentifyKeyReq();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocolBuffer.IdentifyKeyReq.getDescriptor();
      }
      
      public ProtocolBuffer.IdentifyKeyReq getDefaultInstanceForType() {
        return ProtocolBuffer.IdentifyKeyReq.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ProtocolBuffer.IdentifyKeyReq build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ProtocolBuffer.IdentifyKeyReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ProtocolBuffer.IdentifyKeyReq buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ProtocolBuffer.IdentifyKeyReq returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocolBuffer.IdentifyKeyReq) {
          return mergeFrom((ProtocolBuffer.IdentifyKeyReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtocolBuffer.IdentifyKeyReq other) {
        if (other == ProtocolBuffer.IdentifyKeyReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:IdentifyKeyReq)
    }
    
    static {
      defaultInstance = new IdentifyKeyReq(true);
      ProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:IdentifyKeyReq)
  }
  
  public static final class RegisterLocationReq extends
      com.google.protobuf.GeneratedMessage {
    // Use RegisterLocationReq.newBuilder() to construct.
    private RegisterLocationReq() {
      initFields();
    }
    private RegisterLocationReq(boolean noInit) {}
    
    private static final RegisterLocationReq defaultInstance;
    public static RegisterLocationReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegisterLocationReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolBuffer.internal_static_RegisterLocationReq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolBuffer.internal_static_RegisterLocationReq_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ProtocolBuffer.RegisterLocationReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.RegisterLocationReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.RegisterLocationReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtocolBuffer.RegisterLocationReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ProtocolBuffer.RegisterLocationReq result;
      
      // Construct using ProtocolBuffer.RegisterLocationReq.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ProtocolBuffer.RegisterLocationReq();
        return builder;
      }
      
      protected ProtocolBuffer.RegisterLocationReq internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ProtocolBuffer.RegisterLocationReq();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocolBuffer.RegisterLocationReq.getDescriptor();
      }
      
      public ProtocolBuffer.RegisterLocationReq getDefaultInstanceForType() {
        return ProtocolBuffer.RegisterLocationReq.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ProtocolBuffer.RegisterLocationReq build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ProtocolBuffer.RegisterLocationReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ProtocolBuffer.RegisterLocationReq buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ProtocolBuffer.RegisterLocationReq returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocolBuffer.RegisterLocationReq) {
          return mergeFrom((ProtocolBuffer.RegisterLocationReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtocolBuffer.RegisterLocationReq other) {
        if (other == ProtocolBuffer.RegisterLocationReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:RegisterLocationReq)
    }
    
    static {
      defaultInstance = new RegisterLocationReq(true);
      ProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RegisterLocationReq)
  }
  
  public static final class RegisterLocationRes extends
      com.google.protobuf.GeneratedMessage {
    // Use RegisterLocationRes.newBuilder() to construct.
    private RegisterLocationRes() {
      initFields();
    }
    private RegisterLocationRes(boolean noInit) {}
    
    private static final RegisterLocationRes defaultInstance;
    public static RegisterLocationRes getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegisterLocationRes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolBuffer.internal_static_RegisterLocationRes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolBuffer.internal_static_RegisterLocationRes_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ProtocolBuffer.RegisterLocationRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.RegisterLocationRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ProtocolBuffer.RegisterLocationRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ProtocolBuffer.RegisterLocationRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtocolBuffer.RegisterLocationRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ProtocolBuffer.RegisterLocationRes result;
      
      // Construct using ProtocolBuffer.RegisterLocationRes.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ProtocolBuffer.RegisterLocationRes();
        return builder;
      }
      
      protected ProtocolBuffer.RegisterLocationRes internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ProtocolBuffer.RegisterLocationRes();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocolBuffer.RegisterLocationRes.getDescriptor();
      }
      
      public ProtocolBuffer.RegisterLocationRes getDefaultInstanceForType() {
        return ProtocolBuffer.RegisterLocationRes.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ProtocolBuffer.RegisterLocationRes build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ProtocolBuffer.RegisterLocationRes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ProtocolBuffer.RegisterLocationRes buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ProtocolBuffer.RegisterLocationRes returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocolBuffer.RegisterLocationRes) {
          return mergeFrom((ProtocolBuffer.RegisterLocationRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ProtocolBuffer.RegisterLocationRes other) {
        if (other == ProtocolBuffer.RegisterLocationRes.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:RegisterLocationRes)
    }
    
    static {
      defaultInstance = new RegisterLocationRes(true);
      ProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RegisterLocationRes)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_InstantMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InstantMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicKey_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PublicKey_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterKeyReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegisterKeyReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterKeyRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegisterKeyRes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_IdentifyKeyReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IdentifyKeyReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterLocationReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegisterLocationReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterLocationRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegisterLocationRes_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protobuf/ProtocolBuffer.proto\"\"\n\016Insta" +
      "ntMessage\022\020\n\010contents\030\001 \002(\t\"1\n\tPublicKey" +
      "\022\020\n\010encoding\030\001 \002(\t\022\022\n\npublic_key\030\002 \002(\014\"/" +
      "\n\nClientInfo\022\017\n\007version\030\001 \001(\t\022\020\n\010locatio" +
      "n\030\002 \001(\t\"4\n\016RegisterKeyReq\022\020\n\010username\030\001 " +
      "\002(\t\022\020\n\010password\030\002 \002(\t\"\020\n\016RegisterKeyRes\"" +
      "\020\n\016IdentifyKeyReq\"\025\n\023RegisterLocationReq" +
      "\"\025\n\023RegisterLocationRes"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_InstantMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_InstantMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_InstantMessage_descriptor,
              new java.lang.String[] { "Contents", },
              ProtocolBuffer.InstantMessage.class,
              ProtocolBuffer.InstantMessage.Builder.class);
          internal_static_PublicKey_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PublicKey_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PublicKey_descriptor,
              new java.lang.String[] { "Encoding", "PublicKey", },
              ProtocolBuffer.PublicKey.class,
              ProtocolBuffer.PublicKey.Builder.class);
          internal_static_ClientInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ClientInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClientInfo_descriptor,
              new java.lang.String[] { "Version", "Location", },
              ProtocolBuffer.ClientInfo.class,
              ProtocolBuffer.ClientInfo.Builder.class);
          internal_static_RegisterKeyReq_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_RegisterKeyReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RegisterKeyReq_descriptor,
              new java.lang.String[] { "Username", "Password", },
              ProtocolBuffer.RegisterKeyReq.class,
              ProtocolBuffer.RegisterKeyReq.Builder.class);
          internal_static_RegisterKeyRes_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_RegisterKeyRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RegisterKeyRes_descriptor,
              new java.lang.String[] { },
              ProtocolBuffer.RegisterKeyRes.class,
              ProtocolBuffer.RegisterKeyRes.Builder.class);
          internal_static_IdentifyKeyReq_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_IdentifyKeyReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_IdentifyKeyReq_descriptor,
              new java.lang.String[] { },
              ProtocolBuffer.IdentifyKeyReq.class,
              ProtocolBuffer.IdentifyKeyReq.Builder.class);
          internal_static_RegisterLocationReq_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_RegisterLocationReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RegisterLocationReq_descriptor,
              new java.lang.String[] { },
              ProtocolBuffer.RegisterLocationReq.class,
              ProtocolBuffer.RegisterLocationReq.Builder.class);
          internal_static_RegisterLocationRes_descriptor =
            getDescriptor().getMessageTypes().get(7);
          internal_static_RegisterLocationRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RegisterLocationRes_descriptor,
              new java.lang.String[] { },
              ProtocolBuffer.RegisterLocationRes.class,
              ProtocolBuffer.RegisterLocationRes.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
